### ISSUE TITLE
'snapchat_flutter_plugin/SnapchatFlutterPlugin.h' file not found    

### ISSUE THREAD

**Issue by PanikPlunder** [sukhkmr19/flutter_snapchat#2]
Hi,

I'm getting following error when I try to use the plugin:

    /Users/******************/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'snapchat_flutter_plugin/SnapchatFlutterPlugin.h' file not found
    #import <snapchat_flutter_plugin/SnapchatFlutterPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

I'm using the latest plugin (0.0.3+1)

Any idea what I did wrong?

More info:
I've setup a demo flutter project with kotlin and swift support and followed your steps. 

Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/***************/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.7.5

**Comment by sukhkmr19** [comment]
please use legacy build system
