### ISSUE TITLE
Something went wrong.Please try again

### ISSUE THREAD

**Issue by imdarpn** [sukhkmr19/flutter_snapchat#6]
![device-2020-08-07-150759](https://user-images.githubusercontent.com/13308830/89634135-8089f000-d8c2-11ea-9ae2-dc1339c2658f.png)
I am using this package and try to login with a snap I am getting this error

**Comment by L3thal14** [comment]
Hey.. I am facing the same error. I saw your issue in the other snapchat flutter plugin repo as well.. Were you able to fix this @imdarpn ?

**Comment by imdarpn** [comment]
No @L3thal14

**Comment by surajprasad57** [comment]
I am also facing the same issue.... Tried all possible ways..But no help.. Any help would be really appretiated

**Comment by surajprasad57** [comment]
My issue fixed..My redirect url was not correct

**Comment by imdarpn** [comment]
@surajprasad57 can you please send me redirect url example?
