### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by imdarpn** [sukhkmr19/flutter_snapchat#7]
while creating iOS build getting this issue:

`
Xcode's output:
↳
    /Users/home/AndroidStudioProjects/filos-app/ios/Runner/AppDelegate.swift:17:12: error: cannot find 'SCSDKLoginClient' in scope
        return SCSDKLoginClient.application(app, open: url, options: options)
               ^~~~~~~~~~~~~~~~
    /Users/home/AndroidStudioProjects/filos-app/ios/Runner/AppDelegate.swift:17:12: error: cannot find 'SCSDKLoginClient' in scope
        return SCSDKLoginClient.application(app, open: url, options: options)
               ^~~~~~~~~~~~~~~~
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Runner' from project 'Runner')

Encountered error while building for device.
`

**Comment by dp-IED** [comment]
Please look up the error you're getting... I've ran into it too and it literally took me 10 seconds to find a relevant stackoverflow article

**Comment by developer-farhan** [comment]
I think I figured it out replace your appdelegate with this 

import UIKit
import Flutter
import SCSDKLoginKit

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }


}

func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
      if SCSDKLoginClient.application(app, open: url, options: options) {
          return true
      }
      return true
  }

**Comment by developer-farhan** [comment]
but im getting no results printed I can not see users bitmoji url or their snap name 

 onPressed: () async {
            await SnapchatFlutterPlugin.snapchatLogin.then((onValue) {
              print(onValue);
            }).catchError((e) {
              print(e);
            });
          },

**Comment by dp-IED** [comment]
I personally have moved on from this package and have built a simple website using login kit web. I interact with it through a webview and collect the token using regex on the urls.

**Comment by developer-farhan** [comment]
can you share it please?

**Comment by sukhkmr19** [comment]
Hi ColleSerre,

sorry i am not able to update the plugin because of some reason, you may get the code from repo and update as per the new documentation of snapchat login.
Thanks.
